export const GET_PAY_ACCS_LIST_SUCCEED = "GET_PAY_ACCS_LIST_SUCCEED";

export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";

export const OPEN_OTP_DIALOG = "OPEN_OTP_DIALOG";

export const CLOSE_OTP_DIALOG = "CLOSE_OTP_DIALOG";

export const HANDLE_TRANSFER_SUCCEED = "HANDLE_TRANSFER_SUCCEED";

export const HANDLE_TRANSFER_ERROR = "HANDLE_TRANSFER_ERROR";
