export const GET_PAY_ACCS_LIST_SUCCEED = "GET_PAY_ACCS_LIST_SUCCEED";

export const OPEN_CLOSE_PAY_ACC_DIALOG = "OPEN_CLOSE_PAY_ACC_DIALOG";

export const CLOSE_CLOSE_PAY_ACC_DIALOG = "CLOSE_CLOSE_PAY_ACC_DIALOG";

export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";

export const HANDLE_CLOSE_PAY_ACC_SUCCEED = "HANDLE_CLOSE_PAY_ACC_SUCCEED";

export const HANDLE_CLOSE_PAY_ACC_ERROR = "HANDLE_CLOSE_PAY_ACC_ERROR";

export const OPEN_VIEW_HISTORY_DIALOG = "OPEN_VIEW_HISTORY_DIALOG"

export const CLOSE_VIEW_HISTORY_DIALOG = "CLOSE_VIEW_HISTORY_DIALOG";
